### ISSUE TITLE
How will this plugin benefit me?

### ISSUE THREAD

**Issue by Sal-gamer** [GrapheneCt/gpu_es4_kernel_ext#1]
"GPU kernel driver extension for PS Vita

•Removes render target limit
•Removes sync object limit"

Will this plugin help PS Vita render faster?  Will vita be able to render more things at the same time?  Would it help to have less things suddenly appear on the screen?  Once in gravity rush I entered a building that took a while to render when jumping in gravity  and I entered a building out of nowhere, I would appreciate it if you could explain it to me

**Comment by GrapheneCt** [comment]
No, this plugin doesn't improve rendering performance.

**Comment by Sal-gamer** [comment]
what is it for then?

**Comment by GrapheneCt** [comment]
It's only for developers.
